on: [pull_request, push]

name: CI

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azohra/shell-linter@v0.3.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build LLVM
        run: |
          image='${{ github.actor }}/cross-xtensa:llvm'
          docker pull "${image}" || true
          docker build --pull --cache-from "${image}" -t "${image}" --target llvm .
      - name: Build Rust
        run: |
          image='${{ github.actor }}/cross-xtensa:rust'
          docker pull "${image}" || true
          docker build --pull --cache-from '${{ github.actor }}/cross-xtensa:llvm' --cache-from "${image}" -t "${image}" --target rust .
      - name: Build IDF
        run: |
          image='${{ github.actor }}/cross-xtensa:idf'
          docker pull "${image}" || true
          docker build --pull --cache-from '${{ github.actor }}/cross-xtensa:llvm' --cache-from "${image}" -t "${image}" --target rust .
      - name: Log into Docker Hub
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u ${{ github.actor }} --password-stdin
      - name: Push LLVM
        run: docker push '${{ github.actor }}/cross-xtensa:llvm'
      - name: Push Rust
        run: docker push '${{ github.actor }}/cross-xtensa:rust'
      - name: Push IDF
        run: docker push '${{ github.actor }}/cross-xtensa:idf'
