on: [pull_request, push]

name: CI

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azohra/shell-linter@v0.3.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build LLVM
        run: docker build -t '${{ github.actor }}/cross-xtensa:llvm' -f llvm.Dockerfile .
      - name: Log into registry
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u ${{ github.actor }} --password-stdin
      - name: Push LLVM
        run: docker push '${{ github.actor }}/cross-xtensa:llvm'
